---
title: "Surveymonkey data exploration"
author: "Sarabeth Mathis"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

library(tidyverse)
library(here)

survey_monkey <- read.csv(here("data", "surveymonkey_sick_2022-08-01_2024-03-31.csv"))
```

```{r find flu data}

#remove covid variables, try to select only relevant flu
flu_sm <- survey_monkey %>% 
  select(contains("flu"), #tbh I have no idea if you can just use one contain and c() all of these words in there
         contains("influenza"), 
         contains("ST"), 
         contains("age"), 
         contains("date"), 
         contains("professional"), 
         contains("cold"), 
         contains("testing"), 
         contains("symptom"), 
         contains("condition"), 
         contains("antiviral"), 
         -contains("covid"),  
         -contains("c19"))

#range(as.Date(flu_sm$date_created)) #dates ranged from 8/22 - 3/24

#filter out only those who had a flu test or diagnosis or flu antiviral prescription, and did not have "no answer" for tested for flu with na for flu diagnosis and na for prescription received 
flu <- flu_sm %>% 
  filter(!is.na(flu_test_result) | !is.na(received_diagnosis_mc_influenza), 
         flu_test_result != 2 | received_diagnosis_mc_influenza != 0 | prescription_received_mc_flu_antiviral!= 0, 
         !(flu_test_result == 4 & is.na(received_diagnosis_mc_influenza) & is.na(prescription_received_mc_flu_antiviral)), 
         !(flu_test_result == 0 & received_diagnosis_mc_influenza == 0 & prescription_received_mc_flu_antiviral == 0)) %>% 
  mutate(flu_dx_or_t = case_when(flu_test_result == 1 ~ 1, 
                                 received_diagnosis_mc_influenza == 1 ~ 1, 
                                 TRUE ~ 0)) # I debated filtering here for +dx or +test, but some people were waiting on a test, others tested negative but still had +rx

nrow(filter(flu_sm, flu_test_result == 1 | received_diagnosis_mc_influenza == 1))/nrow(flu_sm) #1.7% of people in this dataset had a flu dx or + test
nrow(filter(flu, flu_dx_or_t != 1)) #814 people received an antiviral rx w/o +flu dx or +test
nrow(filter(flu, prescription_received_mc_flu_antiviral == 1))/nrow(flu) #36% of people in this dataset received an antiviral rx, regardless of test or dx
nrow(filter(flu, attempt_fill_prescription_influenza == 1))/nrow(filter(flu, prescription_received_mc_flu_antiviral == 1)) #57% of those who received  rx attempted to get it filled
nrow(filter(flu, able_fill_prescription_influenza == 1))/nrow(filter(flu, attempt_fill_prescription_influenza == 1)) #79% of those who attempted to fill rx were able to get it filled
```


```{r risk conditions}

# I debated starting with the full dataset again, but other than a fludx or test 

flu_conditions <- flu %>% mutate(any_condition = case_when(condition_mc_asthma == 1 ~ 1,
                                                           condition_mc_cancer_last_year == 1 ~ 1, 
                                                           condition_mc_diabetes == 1 ~ 1,
                                                           condition_mc_heart_disease == 1 ~ 1,
                                                           condition_mc_immunosuppressive == 1 ~ 1, 
                                                           condition_mc_kidney_disease == 1 ~ 1, 
                                                           condition_mc_lung_disease  == 1 ~ 1,
                                                           condition_mc_obesity == 1 ~ 1)) %>% filter(any_condition == 1 | age >=65)

nrow(filter(flu_conditions, flu_dx_or_t == 1)) #1047 people are high risk (including age >=65), #735 had a flu dx or +test
nrow(filter(flu_conditions, prescription_received_mc_flu_antiviral == 1))/nrow(filter(flu_conditions, flu_dx_or_t == 1)) # 64% w/+dx or +test received antiviral 
nrow(filter(flu_conditions, attempt_fill_prescription_influenza == 1))/nrow(filter(flu_conditions, prescription_received_mc_flu_antiviral == 1))  #57% attempted to fill rx
nrow(filter(flu_conditions, able_fill_prescription_influenza == 1))/nrow(filter(flu_conditions, attempt_fill_prescription_influenza == 1)) #79% of those who attempted to fill rx were able to get it filled




```
